excluded:
- Pods
- DerivedData
opt_in_rules:
- force_unwrapping
large_tuple: 3
line_length: warning: 100 error: 150
function_body_length: warning: 10
error: 40
type_body_length: warning: 200 error: 400

